server:
  port: 9060
  servlet:
    session:
      timeout: 10s
spring:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/examApp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html
  session:
    timeout: 10s

#  web:
#    resources:
#      static-locations:

logging:
  level:
    org.springframework.web: trace
